-- create table projects (id integer primary autogenerated key, name text, description text, created_at timestamp, updated_at timestamp);
DROP TABLE IF EXISTS projects;
-- Language: tsql
CREATE TABLE projects (
    id int IDENTITY(1,1) PRIMARY KEY,
    project_name nvarchar(255),
    local_git_repo NVARCHAR(255) NOT NULL,
    created_at datetime default getdate(),
    updated_at datetime
);
